package main.java;

import java.io.IOException;

public class Main {
	public static void main(String[] args) throws IOException {
		Inputparser.parseInput("13. juuni. 2016\n" + 
				"14. juuni. 2016\n" + 
				"15. juuni. 2016\n" + 
				"16. juuni. 2016\n" + 
				"17. juuni. 2016\n" + 
				"18. juuni. 2016\n" + 
				"19. juuni. 2016\n" + 
				"Time\n" + 
				"Monday\n" + 
				"Tuesday\n" + 
				"Wednesday\n" + 
				"Thursday\n" + 
				"Friday\n" + 
				"Saturday\n" + 
				"Sunday\n" + 
				"00:00\n" + 
				"Uku/Karel\n" + 
				"German/Kaido/Jürgen\n" + 
				"Eero/Heike/Madis\n" + 
				"Lauri/Anastassia/Helena\n" + 
				"Kaarel/SiimL/Liisa\n" + 
				"Carmel/MartinM\n" + 
				"Henry/Timo\n" + 
				"01:00\n" + 
				"Uku/Karel\n" + 
				"German/Kaido/Jürgen\n" + 
				"Eero/Heike/Madis\n" + 
				"Lauri/Anastassia/Helena\n" + 
				"Kaarel/SiimL/Liisa\n" + 
				"Carmel/MartinM\n" + 
				"Henry/Timo\n" + 
				"02:00\n" + 
				"Uku/Karel\n" + 
				"German/Kaido/Jürgen\n" + 
				"Eero/Heike/Madis\n" + 
				"Lauri/Anastassia/Helena\n" + 
				"Kaarel/SiimL/Liisa\n" + 
				"Carmel/MartinM\n" + 
				"Henry/Timo\n" + 
				"03:00\n" + 
				"Uku/Karel\n" + 
				"German/Kaido/Jürgen\n" + 
				"Eero/Heike/Madis\n" + 
				"Lauri/Anastassia/Helena\n" + 
				"Kaarel/SiimL/Liisa\n" + 
				"Carmel/MartinM\n" + 
				"Henry/Timo\n" + 
				"04:00\n" + 
				"Uku/Karel\n" + 
				"German/Kaido/Jürgen\n" + 
				"Eero/Heike/Madis\n" + 
				"Lauri/Anastassia/Helena\n" + 
				"Kaarel/SiimL/Liisa\n" + 
				"Carmel/MartinM\n" + 
				"Henry/Timo\n" + 
				"05:00\n" + 
				"Uku/Karel\n" + 
				"German/Kaido/Jürgen\n" + 
				"Eero/Heike/Madis\n" + 
				"Lauri/Anastassia/Helena\n" + 
				"Kaarel/SiimL/Liisa\n" + 
				"Carmel/MartinM\n" + 
				"Henry/Timo\n" + 
				"06:00\n" + 
				"Uku/Karel\n" + 
				"German/Kaido/Jürgen\n" + 
				"Eero/Heike/Madis\n" + 
				"Lauri/Anastassia/Helena\n" + 
				"Kaarel/SiimL/Liisa\n" + 
				"Carmel/MartinM\n" + 
				"Henry/Timo\n" + 
				"07:00\n" + 
				"Robert/Carmel/Kaarel/SiimL/Liisa\n" + 
				"Robert/Kaarel/MartinM/Karel/Liisa\n" + 
				"Henry/Carmel/Jürgen/Karel/Liisa\n" + 
				"Henry/Eero/German/Karel/Timo\n" + 
				"Henry/Lauri/Heike/Madis/Helena\n" + 
				"German/Madis/Helena\n" + 
				"German/SiimL/Helena\n" + 
				"08:00\n" + 
				"Sander/Robert/Carmel/Kaarel/SiimL/Liisa\n" + 
				"Sander/Robert/Kaarel/MartinM/Karel/Liisa\n" + 
				"Jürgo/Henry/Carmel/Jürgen/Karel/Liisa\n" + 
				"Jürgo/Henry/Eero/German/Karel/Timo\n" + 
				"Jürgo/Henry/Lauri/Heike/Madis/Helena\n" + 
				"German/Madis/Helena\n" + 
				"German/SiimL/Helena\n" + 
				"09:00\n" + 
				"Sander/Robert/Carmel/Kaarel/SiimL/Liisa\n" + 
				"Sander/Robert/Kaarel/MartinM/Karel/Liisa\n" + 
				"Jürgo/Henry/Carmel/Jürgen/Karel/Liisa\n" + 
				"Jürgo/Henry/Eero/German/Karel/Timo\n" + 
				"Jürgo/Henry/Lauri/Heike/Madis/Helena\n" + 
				"German/Madis/Helena\n" + 
				"German/SiimL/Helena\n" + 
				"10:00\n" + 
				"Sander/Robert/Carmel/Kaarel/SiimL/Liisa\n" + 
				"Sander/Robert/Kaarel/MartinM/Karel/Liisa\n" + 
				"Jürgo/Henry/Carmel/Jürgen/Karel/Liisa\n" + 
				"Jürgo/Henry/Eero/German/Karel/Timo\n" + 
				"Jürgo/Henry/Lauri/Heike/Madis/Helena\n" + 
				"German/Madis/Helena\n" + 
				"German/SiimL/Helena\n" + 
				"11:00\n" + 
				"Sander/Robert/Carmel/Kaarel/SiimL/Liisa\n" + 
				"Sander/Robert/Kaarel/MartinM/Karel/Liisa\n" + 
				"Jürgo/Henry/Carmel/Jürgen/Karel/Liisa\n" + 
				"Jürgo/Henry/Eero/German/Karel/Timo\n" + 
				"Jürgo/Henry/Lauri/Heike/Madis/Helena\n" + 
				"German/Madis/Helena\n" + 
				"German/SiimL/Helena\n" + 
				"12:00\n" + 
				"Sander/Robert/Carmel/Kaarel/SiimL/Liisa\n" + 
				"Sander/Robert/Kaarel/MartinM/Karel/Liisa\n" + 
				"Jürgo/Henry/Carmel/Jürgen/Karel/Liisa\n" + 
				"Jürgo/Henry/Eero/German/Karel/Timo\n" + 
				"Jürgo/Henry/Lauri/Heike/Madis/Helena\n" + 
				"German/Madis/Helena\n" + 
				"German/SiimL/Helena\n" + 
				"13:00\n" + 
				"Sander/Robert/Carmel/Kaarel/SiimL/Liisa\n" + 
				"Sander/Robert/Kaarel/MartinM/Karel/Liisa\n" + 
				"Jürgo/Henry/Carmel/Jürgen/Karel/Liisa\n" + 
				"Jürgo/Henry/Eero/German/Karel/Timo\n" + 
				"Jürgo/Henry/Lauri/Heike/Madis/Helena\n" + 
				"German/Madis/Helena\n" + 
				"German/SiimL/Helena\n" + 
				"14:00\n" + 
				"Sander/Robert/Carmel/Kaarel/SiimL/Liisa\n" + 
				"Sander/Robert/Kaarel/MartinM/Karel/Liisa\n" + 
				"Jürgo/Henry/Carmel/Jürgen/Karel/Liisa\n" + 
				"Jürgo/Henry/Eero/German/Karel/Timo\n" + 
				"Jürgo/Henry/Lauri/Heike/Madis/Helena\n" + 
				"German/Madis/Helena\n" + 
				"German/SiimL/Helena\n" + 
				"15:00\n" + 
				"Jürgo/Sander/Lauri/Eero/Anastassia/Erik/Madis\n" + 
				"Jürgo/Sander/Uku/Lauri/Anastassia/Erik/Timo\n" + 
				"Sander/Jürgo/Uku/Kaarel/MartinM/Kaido/SiimL/Erik\n" + 
				"Sander/Jürgo/Robert/Carmel/MartinM/Kaido/Heike\n" + 
				"Sander/Jürgo/Robert/Eero/Anastassia/Erik/Timo\n" + 
				"Uku/Kaido/Jürgen\n" + 
				"Robert/Heike/Jürgen\n" + 
				"16:00\n" + 
				"Jürgo/Lauri/Eero/Anastassia/Erik/Madis\n" + 
				"Jürgo/Uku/Lauri/Anastassia/Erik/Timo\n" + 
				"Sander/Uku/Kaarel/MartinM/Kaido/SiimL/Erik\n" + 
				"Sander/Robert/Carmel/MartinM/Kaido/Heike\n" + 
				"Sander/Robert/Eero/Anastassia/Erik/Timo\n" + 
				"Uku/Kaido/Jürgen\n" + 
				"Robert/Heike/Jürgen\n" + 
				"17:00\n" + 
				"Jürgo/Lauri/Eero/Anastassia/Erik/Madis\n" + 
				"Jürgo/Uku/Lauri/Anastassia/Erik/Timo\n" + 
				"Sander/Uku/Kaarel/MartinM/Kaido/SiimL/Erik\n" + 
				"Sander/Robert/Carmel/MartinM/Kaido/Heike\n" + 
				"Sander/Robert/Eero/Anastassia/Erik/Timo\n" + 
				"Uku/Kaido/Jürgen\n" + 
				"Robert/Heike/Jürgen\n" + 
				"18:00\n" + 
				"Jürgo/Lauri/Eero/Anastassia/Erik/Madis\n" + 
				"Jürgo/Uku/Lauri/Anastassia/Erik/Timo\n" + 
				"Sander/Uku/Kaarel/MartinM/Kaido/SiimL/Erik\n" + 
				"Sander/Robert/Carmel/MartinM/Kaido/Heike\n" + 
				"Sander/Robert/Eero/Anastassia/Erik/Timo\n" + 
				"Uku/Kaido/Jürgen\n" + 
				"Robert/Heike/Jürgen\n" + 
				"19:00\n" + 
				"Jürgo/Lauri/Eero/Anastassia/Erik/Madis\n" + 
				"Jürgo/Uku/Lauri/Anastassia/Erik/Timo\n" + 
				"Sander/Uku/Kaarel/MartinM/Kaido/SiimL/Erik\n" + 
				"Sander/Robert/Carmel/MartinM/Kaido/Heike\n" + 
				"Sander/Robert/Eero/Anastassia/Erik/Timo\n" + 
				"Uku/Kaido/Jürgen\n" + 
				"Robert/Heike/Jürgen\n" + 
				"20:00\n" + 
				"Jürgo/Lauri/Eero/Anastassia/Erik/Madis\n" + 
				"Jürgo/Uku/Lauri/Anastassia/Erik/Timo\n" + 
				"Sander/Uku/Kaarel/MartinM/Kaido/SiimL/Erik\n" + 
				"Sander/Robert/Carmel/MartinM/Kaido/Heike\n" + 
				"Sander/Robert/Eero/Anastassia/Erik/Timo\n" + 
				"Uku/Kaido/Jürgen\n" + 
				"Robert/Heike/Jürgen\n" + 
				"21:00\n" + 
				"Jürgo/Lauri/Eero/Anastassia/Erik/Madis\n" + 
				"Jürgo/Uku/Lauri/Anastassia/Erik/Timo\n" + 
				"Sander/Uku/Kaarel/MartinM/Kaido/SiimL/Erik\n" + 
				"Sander/Robert/Carmel/MartinM/Kaido/Heike\n" + 
				"Sander/Robert/Eero/Anastassia/Erik/Timo\n" + 
				"Uku/Kaido/Jürgen\n" + 
				"Robert/Heike/Jürgen\n" + 
				"22:00\n" + 
				"Jürgo/Lauri/Eero/Anastassia/Erik/Madis\n" + 
				"Jürgo/Uku/Lauri/Anastassia/Erik/Timo\n" + 
				"Sander/Uku/Kaarel/MartinM/Kaido/SiimL/Erik\n" + 
				"Sander/Robert/Carmel/MartinM/Kaido/Heike\n" + 
				"Sander/Robert/Eero/Anastassia/Erik/Timo\n" + 
				"Uku/Kaido/Jürgen\n" + 
				"Robert/Heike/Jürgen\n" + 
				"23:00\n" + 
				"German/Kaido/Jürgen\n" + 
				"Eero/Heike/Madis\n" + 
				"Lauri/Anastassia/Helena\n" + 
				"Kaarel/SiimL/Liisa\n" + 
				"Carmel/MartinM\n" + 
				"Henry/Timo\n" + 
				"Eero/Anastassia");
	}
//TODO timezone + summer ja winter
//TODO credential location on windows (/home/{USERNAME}/.credentials/calendar-java-quickstart.json)
//TODO kas windowsil splitib eraldi
}
